DROP TABLE IF EXISTS worksessions;

CREATE TABLE worksessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stop_time TIMESTAMP
);
